/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2024_byd.glb 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2024-byd-sealion-7-4eb4a93ae47b47f4b213dd89a0ad89f0
Title: 2024 BYD Sealion 7
*/
import { useGLTF } from '@react-three/drei'

export function Byd_car(props) {
  const { nodes, materials } = useGLTF('/2024_byd.glb')

  
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={0.001}>
          <group scale={100}>
            <mesh geometry={nodes.alloy_rim_B_1_0.geometry} material={materials.rim_B_1} />
            <mesh geometry={nodes.alloy_rim_B_1_0_1.geometry} material={materials.rim_B_1} />
          </group>
          <mesh geometry={nodes.Alloy_chrome_Chrome_Rim_0.geometry} material={materials.Chrome_Rim} scale={100} />
          <mesh geometry={nodes.back_glass_glass1_0.geometry} material={materials.glass1} scale={100} />
          <mesh geometry={nodes.back_indicator_tex_indicator_0.geometry} material={materials.indicator} scale={100} />
          <mesh geometry={nodes.back_part_plas_1_0.geometry} material={materials.plas_1} scale={100} />
          <mesh geometry={nodes.badge_logo_indicator_0.geometry} material={materials.indicator} scale={100} />
          <mesh geometry={nodes.badge_logo001_light_Texture_0.geometry} material={materials.light_Texture} scale={100} />
          <mesh geometry={nodes.black_light_indicator_0.geometry} material={materials.indicator} scale={100} />
          <mesh geometry={nodes.black_light001_black_plas_Light_0.geometry} material={materials.black_plas_Light} scale={100} />
          <mesh geometry={nodes.black_mat_black_plas_Light_0.geometry} material={materials.black_plas_Light} scale={100} />
          <mesh geometry={nodes.black_texture_black_plas_Light_0.geometry} material={materials.black_plas_Light} scale={100} />
          <mesh geometry={nodes.bodypaint_A_carpaint_0.geometry} material={materials.carpaint} scale={100} />
          <mesh geometry={nodes.byd_sealion_badge_crom_chrome_0.geometry} material={materials.chrome} scale={100} />
          <mesh geometry={nodes.Caliper_calipoers_0.geometry} material={materials.calipoers} scale={100} />
          <mesh geometry={nodes.camera_indicator_0.geometry} material={materials.indicator} scale={100} />
          <mesh geometry={nodes.crm_mtl_chrome_0.geometry} material={materials.chrome} scale={100} />
          <mesh geometry={nodes.crom_metal_0.geometry} material={materials.metal} scale={100} />
          <mesh geometry={nodes.crom_part_chorme_lights_0.geometry} material={materials.chorme_lights} scale={100} />
          <mesh geometry={nodes.crome_texture_chorme_lights_0.geometry} material={materials.chorme_lights} scale={100} />
          <mesh geometry={nodes.dhl_strip1_0.geometry} material={materials.strip1} scale={100} />
          <mesh geometry={nodes.disk_disk1_0.geometry} material={materials.disk1} scale={100} />
          <mesh geometry={nodes.front_glass_glass1_0.geometry} material={materials.glass1} scale={100} />
          <mesh geometry={nodes.frount_part_black_black_Sh_0.geometry} material={materials.black_Sh} scale={100} />
          <mesh geometry={nodes.glass_indicator_0.geometry} material={materials.indicator} scale={100} />
          <mesh geometry={nodes.gray_mat_light_Texture_0.geometry} material={materials.light_Texture} scale={100} />
          <mesh geometry={nodes.grill_part_plas_1_0.geometry} material={materials.plas_1} scale={100} />
          <mesh geometry={nodes.grill_uc_under_0.geometry} material={materials.under} scale={100} />
          <mesh geometry={nodes.hl_uc_under_0.geometry} material={materials.under} scale={100} />
          <mesh geometry={nodes.inner_texture_plas_1_0.geometry} material={materials.plas_1} scale={100} />
          <mesh geometry={nodes.Interior_interior_0.geometry} material={materials.interior} scale={100} />
          <mesh geometry={nodes.light_glass_reflector_glass1_0.geometry} material={materials.reflector_glass1} scale={100} />
          <mesh geometry={nodes.light_glass_texture_glass_light_0.geometry} material={materials.glass_light} scale={100} />
          <mesh geometry={nodes.logo_rim_B_1_0.geometry} material={materials.rim_B_1} scale={100} />
          <mesh geometry={nodes.mid_lower_part_black_plas_1_0.geometry} material={materials.plas_1} scale={100} />
          <mesh geometry={nodes.mid_part_black_black_Sh_0.geometry} material={materials.black_Sh} scale={100} />
          <mesh geometry={nodes.mirror_cap_carpaint_0.geometry} material={materials.carpaint} scale={100} />
          <mesh geometry={nodes.mirror_glass_glass1_0.geometry} material={materials.glass1} scale={100} />
          <mesh geometry={nodes.mirror_inner_part_chrome_door_0.geometry} material={materials.chrome_door} scale={100} />
          <mesh geometry={nodes.mirror_light_tex_indicator_0.geometry} material={materials.indicator} scale={100} />
          <mesh geometry={nodes.mirror_plastic_black_Sh_0.geometry} material={materials.black_Sh} scale={100} />
          <mesh geometry={nodes.outer_glass_glass_light_0.geometry} material={materials.glass_light} scale={100} />
          <mesh geometry={nodes.reflector_glass_reflector_glass1_0.geometry} material={materials.reflector_glass1} scale={100} />
          <mesh geometry={nodes.Rim_rim_B_1_0.geometry} material={materials.rim_B_1} scale={100} />
          <mesh geometry={nodes.said_logo_base_black_SH_2_0.geometry} material={materials.black_SH_2} scale={100} />
          <mesh geometry={nodes.sensor_plas_1_0.geometry} material={materials.plas_1} scale={100} />
          <mesh geometry={nodes.sensor001_carpaint_0.geometry} material={materials.carpaint} scale={100} />
          <mesh geometry={nodes.spoiler_spoiler1_0.geometry} material={materials.spoiler1} scale={100} />
          <mesh geometry={nodes.strip_strip1_0.geometry} material={materials.strip1} scale={100} />
          <mesh geometry={nodes.texture_sripe_light_Texture_0.geometry} material={materials.light_Texture} scale={100} />
          <mesh geometry={nodes.TL_Blk_parts_black_R_Lights_0.geometry} material={materials.black_R_Lights} scale={100} />
          <mesh geometry={nodes.TL_BYD_TECH_base_rear_L_0.geometry} material={materials.rear_L} scale={100} />
          <mesh geometry={nodes.TL_Chrome_rear_L_0.geometry} material={materials.rear_L} scale={100} />
          <mesh geometry={nodes.TL_gray_texture_rear_L_0.geometry} material={materials.rear_L} scale={100} />
          <mesh geometry={nodes.TL_light_light_0.geometry} material={materials.light} scale={100} />
          <mesh geometry={nodes.TL_logoBYD_TECH_rear_L_0.geometry} material={materials.rear_L} scale={100} />
          <mesh geometry={nodes.TL_outer_glass_glass_light_Rear_0.geometry} material={materials.glass_light_Rear} scale={100} />
          <mesh geometry={nodes.TL_Texture_rear_L_0.geometry} material={materials.rear_L} scale={100} />
          <mesh geometry={nodes.Tyre_tire_0.geometry} material={materials.tire} scale={100} />
          <mesh geometry={nodes.uc_under_0.geometry} material={materials.under} scale={100} />
          <mesh geometry={nodes.wipers_plas_1_0.geometry} material={materials.plas_1} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/2024_byd.glb')
